setup(
    name="open-gateway",
    version="2022.5.18",
    description="SensiML Open Gateway allows connection to IoT devices for streaming/recording sensor data and video.",
    long_description="README.md",
    long_description_content_type="text/markdown",
    url="https://github.com/sensiml/open-gateway",
    author="SensiML",
    author_email="chris.knorowski@sensiml.com",
    license="BSD 3-Clause License",
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
    ],
    packages=["open_gateway"],
    include_package_data=True,
    install_requires=[
        "flask",
        "flask-wtf",
        "wtforms",
        "flask-cors",
        "pyserial>=2.6",
        "opencv-python",
        "mss",
        "numpy",
        "bleak",
        "nest_asyncio>=0.11.0",
        "requests",
    ],
    entry_points={"console_scripts": ["realpython=open_gateway.__main__:app"]},
)
