// root
export const SET_GLOBAL_LOADER = "SET_GLOBAL_LOADER";

// errors
export const FETCH_DATA_ERROR_MSG = "FETCH_DATA_ERROR_MSG";
export const SET_DATA_ERROR_MSG = "SET_DATA_ERROR_MSG";

// stream
export const START_STREAM_SENSOR_SAGA = "START_STREAM_SENSOR_SAGA";
export const STOP_STREAM_SENSOR_SAGA = "STOP_STREAM_SENSOR_SAGA";
export const SWITCH_STREAM_SENSOR_RECORD_SAGA =
  "SWITCH_STREAM_SENSOR_RECORD_SAGA";
export const SET_IS_STREAMING_SENSOR = "SET_IS_STREAMING_SENSOR";
export const SET_IS_STREAMING_SENSOR_RECORDING =
  "SET_IS_STREAMING_SENSOR_RECORDING";
export const SET_STREAM_SENSOR_DATA_RESET = "SET_STREAM_SENSOR_DATA_RESET";

// sensor data
export const SET_CHUNK_SENSOR_DATA_SAGA = "SET_CHUNK_SENSOR_DATA_SAGA";
export const SET_STREAM_SENSOR_DATA = "SET_STREAM_SENSOR_DATA";
export const SET_STREAM_SENSOR_RECORD_DATA = "SET_STREAM_SENSOR_RECORD_DATA";

// classes data

export const FETCH_CLASS_MAP_IMAGES = "FETCH_CLASS_MAP_IMAGES";
export const SET_CLASS_MAP_IMAGES = "SET_CLASS_MAP_IMAGES";

export const UPDATE_CLOUD_VERSION = "UPDATE_CLOUD_VERSION";
export const UPDATE_LOCAL_VERSION = "UPDATE_LOCAL_VERSION";
export const UPDATE_AVAILABLE = "UPDATE_AVAILABLE";
